[package]
name = "cosmic_vorticity"
version = "1.0.0"
edition = "2021"

[lib]
name = "cosmic_vorticity"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
rayon = "1.7"

[profile.release]
lto = true
opt-level = 3
